### ISSUE TITLE
How do you use SPC in firefox textboxes with your customization?

### ISSUE THREAD

**Issue by codygman** [matthuszagh/emacs#1]
Hi, hope you don't mind a question about your config.

https://github.com/matthuszagh/emacs/blob/5827a8d2ca4e97bf37cfa71dabf9346043573798/layers/exwm-layer.el#L115

When I added this to my config, textboxes in firefox were unusable since all were captured by exwm.

I'm guessing you either always use eww or have something else that fixes this?

**Comment by matthuszagh** [comment]
Happy to answer questions here.

I switch to char-mode when I need to enter space characters. I've bound this to `s-i` (`s` is the system key, so this would be written like `[?\s-i]`). Then I can get back to line-mode with `exwm-reset` (bound to `s-[`). `s-[` is used since it's thematically similar to the vim usage of `C-[`, and I find it easier to press than the actual escape key.

To be honest, this is a point of annoyance in my config, but I prefer it to every solution I've seen in other configs. Ideally, I'd like to be able to use `i` and `C-[` like I use everywhere else. I think theoretically this should be possible with simulation keys, but that's a fair amount of work and it isn't really a priority at the moment.

Does that make sense?

**Comment by codygman** [comment]
Wow! Thanks for the quick response. I'll give that a try for a while and see how it works.

I'll give that a try. I've seen a lot of people just using `S-SPC` as well which I'll do if this is doesn't work out well.

Actually... you just gave me an idea. There a package to edit textboxes in firefox with emacs:

https://addons.mozilla.org/en-US/firefox/addon/edit-with-emacs1/

That could solve at least that issue, but then I'd have issues with work for say... microsoft teams.

I wonder if maybe [emacs application framework](https://github.com/manateelazycat/emacs-application-framework) is applicable in any way here?

I'll look up more about simulation keys to see if I can figure out how that solution might work and see if I have time to implement it.

**Comment by matthuszagh** [comment]
No worries.

EAF looks interesting, thanks for pointing that out. Let me know if you find some better solution.
